name: Build and Publish Library

on:
  workflow_dispatch:
  release:
    types: [created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Updated to Node.js 16
        
      - name: Install Dependencies
        run: npm ci
        
      - name: Build Library
        run: npm run build
        
      - name: Save Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./packages/ui/dist

  publish-npm:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Updated to Node.js 16
          registry-url: 'https://npm.pkg.github.com'
        env:
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
        
      - name: Download Build Artifact
        uses: actions/download-artifact@v2 # Update to the latest version if available
        with:
          name: dist
          path: ./packages/ui/dist-artifact
      
      - name: Publish to npm
        run: npm publish ./packages/ui/dist-artifact --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
